functional:
  - Пользователь должен иметь возможность успешно авторизоваться
  - Авторизованный пользователь должен иметь личный кабинет
  - Авторизованный пользователь должен иметь возможность выбра языка в задании
  - Авторизованный пользователь должен иметь возможность выбора языка программирования
  - Авторизованный пользователь должен иметь возможность принимать участие в игре с другими пользователями
  - Авторизованный пользователь должен иметь возможность принимать участие в игре с другом
  - Авторизованный пользователь должен иметь возможность принимать участие в игре с ботом
  - Авторизованный пользователь должен иметь возможность писать сообщения в чате
  - Пользователь должен иметь возможность просмотра игры других пользователей
  - Пользователь должен иметь возможность просмотра записи игр
  - Авторизованный пользователь должен иметь возможность изменять уровень сложности
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Интерфейс сайта должен быть понятным и удобным
  - Интерфейс сайта должен быть представлен в умеренной цветовой гамме
  - Шрифт сайта должен быть легко читаемым
